server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  # prefer-ip-address: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
spring:
  application:
    name: springcloud-eureka-server
